-- DBA level initialization
CREATE USER test IDENTIFIED BY Us3r_P4ssw0rd;
GRANT CONNECT, RESOURCE TO test;
GRANT ALL PRIVILEGES TO test IDENTIFIED BY Us3r_P4ssw0rd;
GRANT EXECUTE ON DBMS_FLASHBACK TO test;
GRANT EXECUTE ON DBMS_SESSION TO test;
GRANT EXECUTE ON DBMS_RLS TO test;
